set_property SRC_FILE_INFO {cfile:/root/NetFPGA-10G-VC709-2013.3/projects/vc709_reference_nic/vc709_reference_nic.runs/synth_1/.Xil/Vivado-28273-nf-test104.cl.cam.ac.uk/dcp_3/ten_gig_eth_pcs_pma_ip_in_context.xdc rfile:Vivado-28273-nf-test104.cl.cam.ac.uk/dcp_3/ten_gig_eth_pcs_pma_ip_in_context.xdc id:1 order:EARLY scoped_inst:network_inst_0/ten_gig_eth_pcs_pma_inst} [current_design]
set_property SRC_FILE_INFO {cfile:/root/NetFPGA-10G-VC709-2013.3/projects/vc709_reference_nic/vc709_reference_nic.runs/synth_1/.Xil/Vivado-28273-nf-test104.cl.cam.ac.uk/dcp_3/ten_gig_eth_pcs_pma_ip_in_context.xdc rfile:Vivado-28273-nf-test104.cl.cam.ac.uk/dcp_3/ten_gig_eth_pcs_pma_ip_in_context.xdc id:2 order:EARLY scoped_inst:network_inst_1/ten_gig_eth_pcs_pma_inst} [current_design]
set_property SRC_FILE_INFO {cfile:/root/NetFPGA-10G-VC709-2013.3/projects/vc709_reference_nic/vc709_reference_nic.runs/synth_1/.Xil/Vivado-28273-nf-test104.cl.cam.ac.uk/dcp_3/ten_gig_eth_pcs_pma_ip_in_context.xdc rfile:Vivado-28273-nf-test104.cl.cam.ac.uk/dcp_3/ten_gig_eth_pcs_pma_ip_in_context.xdc id:3 order:EARLY scoped_inst:network_inst_2/ten_gig_eth_pcs_pma_inst} [current_design]
set_property SRC_FILE_INFO {cfile:/root/NetFPGA-10G-VC709-2013.3/projects/vc709_reference_nic/vc709_reference_nic.srcs/constrs_1/imports/Downloads/vc709_10g_interface/vc709_10g_interface.srcs/constrs_1/new/vc709_10g_interface.xdc rfile:../../../vc709_reference_nic.srcs/constrs_1/imports/Downloads/vc709_10g_interface/vc709_10g_interface.srcs/constrs_1/new/vc709_10g_interface.xdc id:4} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 3.103 [get_ports txclk322]
set_property src_info {type:SCOPED_XDC file:2 line:1 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 3.103 [get_ports txclk322]
set_property src_info {type:SCOPED_XDC file:3 line:1 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 3.103 [get_ports txclk322]
set_property src_info {type:XDC file:4 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H19 [get_ports clk_ref_p]
set_property src_info {type:XDC file:4 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G18 [get_ports clk_ref_n]
set_property src_info {type:XDC file:4 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH7 [get_ports xphy_refclk_n]
set_property src_info {type:XDC file:4 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH8 [get_ports xphy_refclk_p]
set_property src_info {type:XDC file:4 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_clock_sense -positive clk_divide_reg[1]_i_1/O
set_property src_info {type:XDC file:4 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AU38 [get_ports button_east]
set_property src_info {type:XDC file:4 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB41 [get_ports {sfp_tx_disable[0]}]
set_property src_info {type:XDC file:4 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y42 [get_ports {sfp_tx_disable[1]}]
set_property src_info {type:XDC file:4 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC38 [get_ports {sfp_tx_disable[2]}]
set_property src_info {type:XDC file:4 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC40 [get_ports {sfp_tx_disable[3]}]
set_property src_info {type:XDC file:4 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTHE2_CHANNEL_X1Y12 [get_cells network_inst_0/ten_gig_eth_pcs_pma_inst/inst/gt0_gtwizard_gth_10gbaser_i/gthe2_i]
set_property src_info {type:XDC file:4 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN6 [get_ports xphy0_rxp]
set_property src_info {type:XDC file:4 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP4 [get_ports xphy0_txp]
set_property src_info {type:XDC file:4 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN5 [get_ports xphy0_rxn]
set_property src_info {type:XDC file:4 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP3 [get_ports xphy0_txn]
set_property src_info {type:XDC file:4 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTHE2_CHANNEL_X1Y13 [get_cells network_inst_1/ten_gig_eth_pcs_pma_inst/inst/gt0_gtwizard_gth_10gbaser_i/gthe2_i]
set_property src_info {type:XDC file:4 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM8 [get_ports xphy1_rxp]
set_property src_info {type:XDC file:4 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN2 [get_ports xphy1_txp]
set_property src_info {type:XDC file:4 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM7 [get_ports xphy1_rxn]
set_property src_info {type:XDC file:4 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN1 [get_ports xphy1_txn]
set_property src_info {type:XDC file:4 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTHE2_CHANNEL_X1Y14 [get_cells network_inst_2/ten_gig_eth_pcs_pma_inst/inst/gt0_gtwizard_gth_10gbaser_i/gthe2_i]
set_property src_info {type:XDC file:4 line:99 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL5 [get_ports xphy2_rxn]
set_property src_info {type:XDC file:4 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM3 [get_ports xphy2_txn]
set_property src_info {type:XDC file:4 line:101 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL6 [get_ports xphy2_rxp]
set_property src_info {type:XDC file:4 line:102 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM4 [get_ports xphy2_txp]
set_property src_info {type:XDC file:4 line:104 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTHE2_CHANNEL_X1Y15 [get_cells network_inst_3/ten_gig_eth_pcs_pma_inst/inst/gt0_gtwizard_gth_10gbaser_i/gthe2_i]
set_property src_info {type:XDC file:4 line:105 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ6 [get_ports xphy3_rxp]
set_property src_info {type:XDC file:4 line:106 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL2 [get_ports xphy3_txp]
set_property src_info {type:XDC file:4 line:107 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ5 [get_ports xphy3_rxn]
set_property src_info {type:XDC file:4 line:108 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL1 [get_ports xphy3_txn]
set_property src_info {type:XDC file:4 line:110 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 3.103 -name xphy_rxusrclkout0 [get_pins network_inst_0/ten_gig_eth_pcs_pma_inst/inst/gt0_gtwizard_gth_10gbaser_i/gthe2_i/RXOUTCLK]
set_property src_info {type:XDC file:4 line:111 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 3.103 -name xphy_txusrclkout0 [get_pins network_inst_0/ten_gig_eth_pcs_pma_inst/inst/gt0_gtwizard_gth_10gbaser_i/gthe2_i/TXOUTCLK]
set_property src_info {type:XDC file:4 line:112 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 3.103 -name xphy_rxusrclkout1 [get_pins network_inst_1/ten_gig_eth_pcs_pma_inst/inst/gt0_gtwizard_gth_10gbaser_i/gthe2_i/RXOUTCLK]
set_property src_info {type:XDC file:4 line:113 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 3.103 -name xphy_txusrclkout1 [get_pins network_inst_1/ten_gig_eth_pcs_pma_inst/inst/gt0_gtwizard_gth_10gbaser_i/gthe2_i/TXOUTCLK]
set_property src_info {type:XDC file:4 line:114 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 3.103 -name xphy_rxusrclkout2 [get_pins network_inst_2/ten_gig_eth_pcs_pma_inst/inst/gt0_gtwizard_gth_10gbaser_i/gthe2_i/RXOUTCLK]
set_property src_info {type:XDC file:4 line:115 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 3.103 -name xphy_txusrclkout2 [get_pins network_inst_2/ten_gig_eth_pcs_pma_inst/inst/gt0_gtwizard_gth_10gbaser_i/gthe2_i/TXOUTCLK]
set_property src_info {type:XDC file:4 line:116 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 3.103 -name xphy_rxusrclkout3 [get_pins network_inst_3/ten_gig_eth_pcs_pma_inst/inst/gt0_gtwizard_gth_10gbaser_i/gthe2_i/RXOUTCLK]
set_property src_info {type:XDC file:4 line:117 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 3.103 -name xphy_txusrclkout3 [get_pins network_inst_3/ten_gig_eth_pcs_pma_inst/inst/gt0_gtwizard_gth_10gbaser_i/gthe2_i/TXOUTCLK]
set_property src_info {type:XDC file:4 line:135 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AT35 [get_ports i2c_clk]
set_property src_info {type:XDC file:4 line:141 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AU32 [get_ports i2c_data]
set_property src_info {type:XDC file:4 line:146 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AY42 [get_ports i2c_mux_rst_n]
set_property src_info {type:XDC file:4 line:151 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AT36 [get_ports si5324_rst_n]
set_property src_info {type:XDC file:4 line:174 export:INPUT save:INPUT read:READ} [current_design]
set_clock_groups -name async_rxusrclk_xgemac -asynchronous -group [get_clocks xphy_rxusrclkout?] -group [get_clocks clk156]
set_property src_info {type:XDC file:4 line:176 export:INPUT save:INPUT read:READ} [current_design]
set_clock_groups -name async_txusrclk_xgemac -asynchronous -group [get_clocks xphy_txusrclkout?] -group [get_clocks clk156]
set_property src_info {type:XDC file:4 line:178 export:INPUT save:INPUT read:READ} [current_design]
set_clock_groups -name async_txusrclk_refclk -asynchronous -group [get_clocks xphy_txusrclkout?] -group [get_clocks -include_generated_clocks refclk]
set_property src_info {type:XDC file:4 line:194 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AP37 [get_ports emcclk]
set_property src_info {type:XDC file:4 line:209 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AM39 [get_ports led_0]
set_property src_info {type:XDC file:4 line:210 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AN39 [get_ports led_1]
set_property src_info {type:XDC file:4 line:211 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AR37 [get_ports led_2]
set_property src_info {type:XDC file:4 line:212 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AT37 [get_ports led_3]
set_property src_info {type:XDC file:4 line:213 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AR35 [get_ports led_4]
set_property src_info {type:XDC file:4 line:214 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AP41 [get_ports led_5]
set_property src_info {type:XDC file:4 line:215 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AP42 [get_ports led_6]
set_property src_info {type:XDC file:4 line:216 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AU39 [get_ports led_7]
set_property src_info {type:XDC file:4 line:270 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AV35 [get_ports sys_rst_n]
set_property src_info {type:XDC file:4 line:285 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IBUFDS_GTE2_X1Y11 [get_cells refclk_ibuf]
