# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /root/NetFPGA-10G-VC709-2013.3/projects/vc709_reference_nic/vc709_reference_nic.srcs/sources_1/ip/vc709_pcie_x8_gen3/vc709_pcie_x8_gen3.xci
# IP: The module: 'vc709_pcie_x8_gen3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /root/NetFPGA-10G-VC709-2013.3/projects/vc709_reference_nic/vc709_reference_nic.srcs/sources_1/ip/vc709_pcie_x8_gen3/vc709_pcie_x8_gen3/source/vc709_pcie_x8_gen3-PCIE_X0Y1.xdc
# XDC: The top module name and the constraint reference have the same name: 'vc709_pcie_x8_gen3'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /root/NetFPGA-10G-VC709-2013.3/projects/vc709_reference_nic/vc709_reference_nic.srcs/sources_1/ip/vc709_pcie_x8_gen3/synth/vc709_pcie_x8_gen3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'vc709_pcie_x8_gen3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# IP: /root/NetFPGA-10G-VC709-2013.3/projects/vc709_reference_nic/vc709_reference_nic.srcs/sources_1/ip/vc709_pcie_x8_gen3/vc709_pcie_x8_gen3.xci
# IP: The module: 'vc709_pcie_x8_gen3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /root/NetFPGA-10G-VC709-2013.3/projects/vc709_reference_nic/vc709_reference_nic.srcs/sources_1/ip/vc709_pcie_x8_gen3/vc709_pcie_x8_gen3/source/vc709_pcie_x8_gen3-PCIE_X0Y1.xdc
# XDC: The top module name and the constraint reference have the same name: 'vc709_pcie_x8_gen3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /root/NetFPGA-10G-VC709-2013.3/projects/vc709_reference_nic/vc709_reference_nic.srcs/sources_1/ip/vc709_pcie_x8_gen3/synth/vc709_pcie_x8_gen3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'vc709_pcie_x8_gen3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
