# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

set_property BUFFER_TYPE NONE -quiet [get_ports -quiet -of [get_cells -hier -filter {REF_NAME==cmd_fifo_xgemac_rxif || ORIG_REF_NAME==cmd_fifo_xgemac_rxif}]]
set_property BUFFER_TYPE NONE -quiet [get_ports -quiet -of [get_cells -hier -filter {REF_NAME==axis_async_fifo || ORIG_REF_NAME==axis_async_fifo}]]
set_property BUFFER_TYPE NONE -quiet [get_ports -quiet -of [get_cells -hier -filter {REF_NAME==ten_gig_eth_pcs_pma_ip || ORIG_REF_NAME==ten_gig_eth_pcs_pma_ip}]]
set_property BUFFER_TYPE NONE -quiet [get_ports -quiet -of [get_cells -hier -filter {REF_NAME==ten_gig_eth_mac_ip || ORIG_REF_NAME==ten_gig_eth_mac_ip}]]
set_property BUFFER_TYPE NONE -quiet [get_ports -quiet -of [get_cells -hier -filter {REF_NAME==vc709_pcie_x8_gen3 || ORIG_REF_NAME==vc709_pcie_x8_gen3}]]
set_property BUFFER_TYPE NONE -quiet [get_ports -quiet -of [get_cells -hier -filter {REF_NAME==axi_dma_0 || ORIG_REF_NAME==axi_dma_0}]]
set_property BUFFER_TYPE NONE -quiet [get_ports -quiet -of [get_cells -hier -filter {REF_NAME==nf10_bram_output_queues_0 || ORIG_REF_NAME==nf10_bram_output_queues_0}]]
