# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Downloads/vc709_10g_interface/vc709_10g_interface.srcs/constrs_1/new/vc709_10g_interface.xdc

# IP: ip/cmd_fifo_xgemac_rxif/cmd_fifo_xgemac_rxif.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cmd_fifo_xgemac_rxif || ORIG_REF_NAME==cmd_fifo_xgemac_rxif}]

# IP: ip/axis_async_fifo/axis_async_fifo.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axis_async_fifo || ORIG_REF_NAME==axis_async_fifo}]

# IP: ip/ten_gig_eth_pcs_pma_ip/ten_gig_eth_pcs_pma_ip.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ten_gig_eth_pcs_pma_ip || ORIG_REF_NAME==ten_gig_eth_pcs_pma_ip}]

# IP: ip/ten_gig_eth_mac_ip/ten_gig_eth_mac_ip.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ten_gig_eth_mac_ip || ORIG_REF_NAME==ten_gig_eth_mac_ip}]

# IP: ip/nf10_nic_output_port_lookup_0/nf10_nic_output_port_lookup_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==nf10_nic_output_port_lookup_0 || ORIG_REF_NAME==nf10_nic_output_port_lookup_0}]

# IP: ip/nf10_input_arbiter_0/nf10_input_arbiter_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==nf10_input_arbiter_0 || ORIG_REF_NAME==nf10_input_arbiter_0}]

# IP: ip/nf10_bram_output_queues_0_0/nf10_bram_output_queues_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==nf10_bram_output_queues_0 || ORIG_REF_NAME==nf10_bram_output_queues_0}]

# IP: ip/vc709_pcie_x8_gen3/vc709_pcie_x8_gen3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vc709_pcie_x8_gen3 || ORIG_REF_NAME==vc709_pcie_x8_gen3}]

# IP: ip/axi_dma_0/axi_dma_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_dma_0 || ORIG_REF_NAME==axi_dma_0}]

# XDC: ip/cmd_fifo_xgemac_rxif/cmd_fifo_xgemac_rxif/cmd_fifo_xgemac_rxif.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==cmd_fifo_xgemac_rxif || ORIG_REF_NAME==cmd_fifo_xgemac_rxif}] {/U0 }]/U0 ]]

# XDC: ip/axis_async_fifo/axis_async_fifo/axis_async_fifo_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==axis_async_fifo || ORIG_REF_NAME==axis_async_fifo}] {/U0 }]/U0 ]]

# XDC: ip/axis_async_fifo/axis_async_fifo/axis_async_fifo.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==axis_async_fifo || ORIG_REF_NAME==axis_async_fifo}] {/U0 }]/U0 ]]

# XDC: ip/ten_gig_eth_pcs_pma_ip/synth/ten_gig_eth_pcs_pma_ip_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ten_gig_eth_pcs_pma_ip || ORIG_REF_NAME==ten_gig_eth_pcs_pma_ip}] {/inst }]/inst ]]

# XDC: ip/ten_gig_eth_pcs_pma_ip/synth/ten_gig_eth_pcs_pma_ip.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ten_gig_eth_pcs_pma_ip || ORIG_REF_NAME==ten_gig_eth_pcs_pma_ip}] {/inst }]/inst ]]

# XDC: ip/ten_gig_eth_mac_ip/synth/ten_gig_eth_mac_ip.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ten_gig_eth_mac_ip || ORIG_REF_NAME==ten_gig_eth_mac_ip}] {/inst }]/inst ]]

# XDC: ip/vc709_pcie_x8_gen3/vc709_pcie_x8_gen3/source/vc709_pcie_x8_gen3-PCIE_X0Y1.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==vc709_pcie_x8_gen3 || ORIG_REF_NAME==vc709_pcie_x8_gen3}] {/inst }]/inst ]]

# XDC: ip/axi_dma_0/axi_dma_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==axi_dma_0 || ORIG_REF_NAME==axi_dma_0}] {/U0 }]/U0 ]]

# XDC: ip/axi_dma_0/axi_dma_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==axi_dma_0 || ORIG_REF_NAME==axi_dma_0}] {/U0 }]/U0 ]]
