# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
create_project -in_memory -part xc7vx690tffg1761-2
set_param project.compositeFile.enableAutoGeneration 0
read_verilog -library verilog {
  /root/NetFPGA-10G-VC709/projects/nf10_input_arbiter_v1_00_a/nf10_input_arbiter_v1_00_a.srcs/small_fifo_v3.v
  /root/NetFPGA-10G-VC709/projects/nf10_input_arbiter_v1_00_a/nf10_input_arbiter_v1_00_a.srcs/fallthrough_small_fifo_v2.v
  /root/NetFPGA-10G-VC709/projects/nf10_input_arbiter_v1_00_a/nf10_input_arbiter_v1_00_a.srcs/nf10_input_arbiter.v
}
read_xdc /root/NetFPGA-10G-VC709/projects/nf10_input_arbiter_v1_00_a/nf10_input_arbiter_v1_00_a.srcs/nf10_input_arbiter_constrs/nf10_input_arbiter_constrs.xdc
set_property used_in_implementation false [get_files /root/NetFPGA-10G-VC709/projects/nf10_input_arbiter_v1_00_a/nf10_input_arbiter_v1_00_a.srcs/nf10_input_arbiter_constrs/nf10_input_arbiter_constrs.xdc]

set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /root/NetFPGA-10G-VC709/projects/nf10_input_arbiter_v1_00_a/nf10_input_arbiter_v1_00_a.data/wt [current_project]
set_property parent.project_dir /root/NetFPGA-10G-VC709/projects/nf10_input_arbiter_v1_00_a [current_project]
synth_design -top nf10_input_arbiter -part xc7vx690tffg1761-2
write_checkpoint nf10_input_arbiter.dcp
report_utilization -file nf10_input_arbiter_utilization_synth.rpt -pb nf10_input_arbiter_utilization_synth.pb
