# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/nf10_nic_output_port_lookup_0/nf10_nic_output_port_lookup_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==nf10_nic_output_port_lookup_0 || ORIG_REF_NAME==nf10_nic_output_port_lookup_0}]

# IP: ip/nf10_input_arbiter_0/nf10_input_arbiter_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==nf10_input_arbiter_0 || ORIG_REF_NAME==nf10_input_arbiter_0}]

# IP: ip/nf10_bram_output_queues_0_0/nf10_bram_output_queues_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==nf10_bram_output_queues_0 || ORIG_REF_NAME==nf10_bram_output_queues_0}]
