# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
create_project -in_memory -part xc7vx690tffg1761-2
set_property board xilinx.com:virtex7:vc709:1.0 [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property ip_repo_paths {
  /root/NetFPGA-10G-VC709/projects/nf10_input_arbiter
  /root/NetFPGA-10G-VC709/projects/nf10_bram_output_queues
  /root/NetFPGA-10G-VC709/projects/nf10_nic_output_port_lookup
  /root/NetFPGA-10G-VC709/projects/nf10_user_datapath
} [current_fileset]

read_ip /root/NetFPGA-10G-VC709/projects/nf10_user_datapath/nf10_user_datapath.srcs/sources_1/ip/nf10_nic_output_port_lookup_0/nf10_nic_output_port_lookup_0.xci
set_property is_locked true [get_files /root/NetFPGA-10G-VC709/projects/nf10_user_datapath/nf10_user_datapath.srcs/sources_1/ip/nf10_nic_output_port_lookup_0/nf10_nic_output_port_lookup_0.xci]

read_ip /root/NetFPGA-10G-VC709/projects/nf10_user_datapath/nf10_user_datapath.srcs/sources_1/ip/nf10_input_arbiter_0/nf10_input_arbiter_0.xci
set_property is_locked true [get_files /root/NetFPGA-10G-VC709/projects/nf10_user_datapath/nf10_user_datapath.srcs/sources_1/ip/nf10_input_arbiter_0/nf10_input_arbiter_0.xci]

read_ip /root/NetFPGA-10G-VC709/projects/nf10_user_datapath/nf10_user_datapath.srcs/sources_1/ip/nf10_bram_output_queues_0_0/nf10_bram_output_queues_0.xci
set_property is_locked true [get_files /root/NetFPGA-10G-VC709/projects/nf10_user_datapath/nf10_user_datapath.srcs/sources_1/ip/nf10_bram_output_queues_0_0/nf10_bram_output_queues_0.xci]

read_verilog /root/NetFPGA-10G-VC709/projects/nf10_user_datapath/nf10_user_datapath.srcs/sources_1/new/nf10_datapath.v
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /root/NetFPGA-10G-VC709/projects/nf10_user_datapath/nf10_user_datapath.data/wt [current_project]
set_property parent.project_dir /root/NetFPGA-10G-VC709/projects/nf10_user_datapath [current_project]
synth_design -top nf10_datapath -part xc7vx690tffg1761-2
write_checkpoint nf10_datapath.dcp
report_utilization -file nf10_datapath_utilization_synth.rpt -pb nf10_datapath_utilization_synth.pb
