# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/vc709_10g_interface.xdc

# IP: ip/cmd_fifo_xgemac_rxif/cmd_fifo_xgemac_rxif.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cmd_fifo_xgemac_rxif || ORIG_REF_NAME==cmd_fifo_xgemac_rxif}]

# IP: ip/axis_async_fifo/axis_async_fifo.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axis_async_fifo || ORIG_REF_NAME==axis_async_fifo}]

# IP: ip/ten_gig_eth_pcs_pma_ip/ten_gig_eth_pcs_pma_ip.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ten_gig_eth_pcs_pma_ip || ORIG_REF_NAME==ten_gig_eth_pcs_pma_ip}]

# IP: ip/ten_gig_eth_mac_ip/ten_gig_eth_mac_ip.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ten_gig_eth_mac_ip || ORIG_REF_NAME==ten_gig_eth_mac_ip}]

# XDC: ip/cmd_fifo_xgemac_rxif/cmd_fifo_xgemac_rxif/cmd_fifo_xgemac_rxif.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==cmd_fifo_xgemac_rxif || ORIG_REF_NAME==cmd_fifo_xgemac_rxif}] {/U0 }]/U0 ]]

# XDC: ip/axis_async_fifo/axis_async_fifo/axis_async_fifo_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==axis_async_fifo || ORIG_REF_NAME==axis_async_fifo}] {/U0 }]/U0 ]]

# XDC: ip/axis_async_fifo/axis_async_fifo/axis_async_fifo.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==axis_async_fifo || ORIG_REF_NAME==axis_async_fifo}] {/U0 }]/U0 ]]

# XDC: ip/ten_gig_eth_pcs_pma_ip/synth/ten_gig_eth_pcs_pma_ip_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ten_gig_eth_pcs_pma_ip || ORIG_REF_NAME==ten_gig_eth_pcs_pma_ip}] {/inst }]/inst ]]

# XDC: ip/ten_gig_eth_pcs_pma_ip/synth/ten_gig_eth_pcs_pma_ip.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ten_gig_eth_pcs_pma_ip || ORIG_REF_NAME==ten_gig_eth_pcs_pma_ip}] {/inst }]/inst ]]

# XDC: ip/ten_gig_eth_mac_ip/synth/ten_gig_eth_mac_ip.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ten_gig_eth_mac_ip || ORIG_REF_NAME==ten_gig_eth_mac_ip}] {/inst }]/inst ]]
