# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
create_project -in_memory -part xc7vx690tffg1761-2
set_param project.compositeFile.enableAutoGeneration 0

read_ip /root/Downloads/vc709_10g_interface/vc709_10g_interface.srcs/sources_1/ip/cmd_fifo_xgemac_rxif/cmd_fifo_xgemac_rxif.xci
set_property used_in_implementation false [get_files -all /root/Downloads/vc709_10g_interface/vc709_10g_interface.srcs/sources_1/ip/cmd_fifo_xgemac_rxif/cmd_fifo_xgemac_rxif/example_design/cmd_fifo_xgemac_rxif_exdes.xdc]
set_property used_in_implementation false [get_files -all /root/Downloads/vc709_10g_interface/vc709_10g_interface.srcs/sources_1/ip/cmd_fifo_xgemac_rxif/cmd_fifo_xgemac_rxif/cmd_fifo_xgemac_rxif.xdc]
set_property used_in_implementation false [get_files -all /root/Downloads/vc709_10g_interface/vc709_10g_interface.srcs/sources_1/ip/cmd_fifo_xgemac_rxif/cmd_fifo_xgemac_rxif/cmd_fifo_xgemac_rxif_ooc.xdc]
set_property is_locked true [get_files /root/Downloads/vc709_10g_interface/vc709_10g_interface.srcs/sources_1/ip/cmd_fifo_xgemac_rxif/cmd_fifo_xgemac_rxif.xci]

read_ip /root/Downloads/vc709_10g_interface/vc709_10g_interface.srcs/sources_1/ip/axis_async_fifo/axis_async_fifo.xci
set_property used_in_implementation false [get_files -all /root/Downloads/vc709_10g_interface/vc709_10g_interface.srcs/sources_1/ip/axis_async_fifo/axis_async_fifo/example_design/axis_async_fifo_exdes.xdc]
set_property used_in_implementation false [get_files -all /root/Downloads/vc709_10g_interface/vc709_10g_interface.srcs/sources_1/ip/axis_async_fifo/axis_async_fifo/axis_async_fifo_clocks.xdc]
set_property used_in_implementation false [get_files -all /root/Downloads/vc709_10g_interface/vc709_10g_interface.srcs/sources_1/ip/axis_async_fifo/axis_async_fifo/axis_async_fifo.xdc]
set_property used_in_implementation false [get_files -all /root/Downloads/vc709_10g_interface/vc709_10g_interface.srcs/sources_1/ip/axis_async_fifo/axis_async_fifo/axis_async_fifo_ooc.xdc]
set_property is_locked true [get_files /root/Downloads/vc709_10g_interface/vc709_10g_interface.srcs/sources_1/ip/axis_async_fifo/axis_async_fifo.xci]

read_ip /root/Downloads/vc709_10g_interface/vc709_10g_interface.srcs/sources_1/ip/ten_gig_eth_pcs_pma_ip/ten_gig_eth_pcs_pma_ip.xci
set_property used_in_implementation false [get_files -all /root/Downloads/vc709_10g_interface/vc709_10g_interface.srcs/sources_1/ip/ten_gig_eth_pcs_pma_ip/example_design/ten_gig_eth_pcs_pma_ip_example_design.xdc]
set_property used_in_implementation false [get_files -all /root/Downloads/vc709_10g_interface/vc709_10g_interface.srcs/sources_1/ip/ten_gig_eth_pcs_pma_ip/synth/ten_gig_eth_pcs_pma_ip_clocks.xdc]
set_property used_in_implementation false [get_files -all /root/Downloads/vc709_10g_interface/vc709_10g_interface.srcs/sources_1/ip/ten_gig_eth_pcs_pma_ip/synth/ten_gig_eth_pcs_pma_ip_ooc.xdc]
set_property used_in_implementation false [get_files -all /root/Downloads/vc709_10g_interface/vc709_10g_interface.srcs/sources_1/ip/ten_gig_eth_pcs_pma_ip/synth/ten_gig_eth_pcs_pma_ip.xdc]
set_property is_locked true [get_files /root/Downloads/vc709_10g_interface/vc709_10g_interface.srcs/sources_1/ip/ten_gig_eth_pcs_pma_ip/ten_gig_eth_pcs_pma_ip.xci]

read_ip /root/Downloads/vc709_10g_interface/vc709_10g_interface.srcs/sources_1/ip/ten_gig_eth_mac_ip/ten_gig_eth_mac_ip.xci
set_property used_in_implementation false [get_files -all /root/Downloads/vc709_10g_interface/vc709_10g_interface.srcs/sources_1/ip/ten_gig_eth_mac_ip/example_design/ten_gig_eth_mac_ip_example_design.xdc]
set_property used_in_implementation false [get_files -all /root/Downloads/vc709_10g_interface/vc709_10g_interface.srcs/sources_1/ip/ten_gig_eth_mac_ip/synth/ten_gig_eth_mac_ip.xdc]
set_property used_in_implementation false [get_files -all /root/Downloads/vc709_10g_interface/vc709_10g_interface.srcs/sources_1/ip/ten_gig_eth_mac_ip/ten_gig_eth_mac_ip_ooc.xdc]
set_property is_locked true [get_files /root/Downloads/vc709_10g_interface/vc709_10g_interface.srcs/sources_1/ip/ten_gig_eth_mac_ip/ten_gig_eth_mac_ip.xci]

read_verilog {
  /root/Downloads/vc709_10g_interface/vc709_10g_interface.srcs/sources_1/common/synchronizer_simple.v
  /root/Downloads/vc709_10g_interface/vc709_10g_interface.srcs/sources_1/tx_interface.v
  /root/Downloads/vc709_10g_interface/vc709_10g_interface.srcs/sources_1/ten_gig_eth_pcs_pma_ip_GT_Common_wrapper.v
  /root/Downloads/vc709_10g_interface/vc709_10g_interface.srcs/sources_1/rx_interface.v
  /root/Downloads/vc709_10g_interface/vc709_10g_interface.srcs/sources_1/network_module.v
  /root/Downloads/vc709_10g_interface/vc709_10g_interface.srcs/sources_1/imports/network_interface/xgbaser_gt_same_quad_wrapper.v
  /root/Downloads/vc709_10g_interface/vc709_10g_interface.srcs/sources_1/vc709_10g_interface.v
}
read_vhdl {
  /root/Downloads/vc709_10g_interface/vc709_10g_interface.srcs/sources_1/clock_control/kcpsm6.vhd
  /root/Downloads/vc709_10g_interface/vc709_10g_interface.srcs/sources_1/clock_control/clock_control_program.vhd
  /root/Downloads/vc709_10g_interface/vc709_10g_interface.srcs/sources_1/clock_control/clock_control.vhd
}
read_xdc /root/Downloads/vc709_10g_interface/vc709_10g_interface.srcs/constrs_1/new/vc709_10g_interface.xdc
set_property used_in_implementation false [get_files /root/Downloads/vc709_10g_interface/vc709_10g_interface.srcs/constrs_1/new/vc709_10g_interface.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /root/Downloads/vc709_10g_interface/vc709_10g_interface.data/wt [current_project]
set_property parent.project_dir /root/Downloads/vc709_10g_interface [current_project]
synth_design -top vc709_10g_interface -part xc7vx690tffg1761-2
write_checkpoint vc709_10g_interface.dcp
report_utilization -file vc709_10g_interface_utilization_synth.rpt -pb vc709_10g_interface_utilization_synth.pb
